// START OF CODE FOR src/app/layout.js
import './globals.css';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head> {}
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" rel="stylesheet" />
      </head>
      <body className="bg-white min-h-screen">{children}</body>
    </html>
  )
}
// END OF CODE FOR src/app/layout.js
