# Generated by Django 5.2.3 on 2025-06-26 18:15

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Site name or identifier', max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Site coordinates (WGS84)', srid=4326)),
                ('analysis_radius', models.IntegerField(default=500, help_text='Analysis radius in meters', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Analysis',
                'verbose_name_plural': 'Site Analyses',
            },
        ),
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epw_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('temperature_data', models.JSONField(default=dict, help_text='Temperature statistics')),
                ('precipitation_data', models.JSONField(default=dict, help_text='Precipitation data')),
                ('wind_data', models.JSONField(default=dict, help_text='Wind patterns')),
                ('solar_data', models.JSONField(default=dict, help_text='Solar radiation data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='climate_data', to='environmental_analysis.siteanalysis')),
            ],
            options={
                'verbose_name': 'Climate Data',
                'verbose_name_plural': 'Climate Data',
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('landuse', 'Land Use'), ('natural', 'Natural Feature'), ('leisure', 'Leisure Area'), ('highway', 'Transportation'), ('building', 'Building'), ('amenity', 'Amenity')], max_length=20)),
                ('osm_id', models.BigIntegerField(help_text='OpenStreetMap ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(help_text='Feature geometry', srid=4326)),
                ('properties', models.JSONField(default=dict, help_text='OSM tags and properties')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='environmental_analysis.siteanalysis')),
            ],
            options={
                'indexes': [models.Index(fields=['feature_type'], name='environment_feature_92fd9d_idx'), models.Index(fields=['osm_id'], name='environment_osm_id_3efb9c_idx')],
                'unique_together': {('site_analysis', 'osm_id')},
            },
        ),
    ]
